### ISSUE TITLE
Publish on creation of tag

### ISSUE THREAD

**Issue by Ardesco** [samuelmeuli/action-maven-publish#11]
Have you thought about tweaking this so that it only released when you push a new tag?

```
on:
  push:
    tags:
    - '*'
```

Would be good to do a `mvn versions:set tag="<tag>"` as part of the build as well.  Then you could push to master to deploy snapshots, and when you are ready to actually release, just tag up a release.

**Comment by kristjank** [comment]
also native gradle support included, or configurable?

**Comment by samuelmeuli** [comment]
> Have you thought about tweaking this so that it only released when you push a new tag?

@ardesco This is controlled by your workflow, not the action.

> Would be good to do a mvn versions:set tag="<tag>" as part of the build as well. Then you could push to master to deploy snapshots, and when you are ready to actually release, just tag up a release.

This action is only responsible for publishing artifacts, not creating releases. This should handled with custom steps in your GitHub Actions workflow instead.

**Comment by samuelmeuli** [comment]
> also native gradle support included, or configurable?

@kristjank Is this related to this issue?

**Comment by Ardesco** [comment]
Agreed that this is something controlled by workflow, however it is a valid suggestion in my mind.  

If you want to deploy to maven central you need to provide a new version number that has not already been deployed, you can't redeploy the same version again and again.  

You can publish snapshots again and again which is what I would suggest regular a regular publish job on master would be good for.

**Comment by samuelmeuli** [comment]
It's definitely a valid use case. But this aciton is only responsible for handling a part of it.

It only deals with publishing artifacts. It is left to the user to decide whether they want to create a release (i.e. update the POM version and create a Git tag) on their machine or in an earlier step of the GitHub Actions workflow.

> If you want to deploy to maven central you need to provide a new version number that has not already been deployed, you can't redeploy the same version again and again.

There should only be one commit with a specific non-snapshot version in your POM. If you're using a tool like the [Maven Release Plugin](https://maven.apache.org/maven-release/maven-release-plugin), this should be handled for you.
