### ISSUE TITLE
Make profiles configurable

### ISSUE THREAD

**Issue by leohilbert** [samuelmeuli/action-maven-publish#12]
Hi, first up: many thanks for this action, helped me out a ton! :)
I want to deploy an artifact without a POM using the "gpg:sign-and-deploy-file".
This works quite nice with your plugin, by changing the "maven_goals_phases" and "maven_args". However there is no way to remove the "activate-profiles"-property form the mvn-call. This causes the mvn deploy to fail, because it does not find a pom.xml
For now I forked the repo and removed the property from the index.js, but it would be cool if it would be configurable. Something like a "useDeployProfile" that is true by default.

I can open a pull-request if you want, I'm just not really experienced with building Github Actions and don't want to break something :P 
Thanks!

**Comment by samuelmeuli** [comment]
Hi @leohilbert,

I would suggest introducing a `maven_profiles` option instead, with `"deploy"` as the default value.

A PR would be great, ideally with a test for your use case :)

**Comment by XDean** [comment]
Hi @samuelmeuli , I have created a PR. Please review it.
