### ISSUE TITLE
Deployment of snapshot versions

### ISSUE THREAD

**Issue by renedewaele** [samuelmeuli/action-maven-publish#14]
Hi,

I noticed that deployment is performed even if the version in the pom.xml file is 0-SNAPSHOT. However, in the readme is stated:

> If your pom.xml file contains a non-snapshot version number and all tests pass, your package will be deployed automatically.

Do I misunderstand the readme?

Thanks!

**Comment by samuelmeuli** [comment]
This sentence (wrongfully) assumes that the Nexus Staging Maven Plugin is used for deployment. With Nexus, the described behavior is indeed correct. I will clarify that.
